name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up -d
          echo "⏳ Waiting for containers to initialize..."
          sleep 60  # เพิ่มเวลาเป็น 60 วินาทีเพื่อให้ db service พร้อม

      - name: Check Docker Compose status
        run: docker compose ps  # ตรวจสอบสถานะของ container

      - name: Run test inside web container
        run: |
          docker compose exec -it web curl -s http://localhost:5000/api/users

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down
